create or replace function public.build_subordinate_clause_foundation_v4(p_sentence jsonb,p_release_code text)
returns jsonb language plpgsql stable security invoker set search_path='public','pg_catalog' as $$
declare base jsonb; a jsonb:=coalesce(p_sentence->'analysis','{}'::jsonb); mwe jsonb:=coalesce(a#>'{language_graph,multiword_function_expression_v1}','{}'::jsonb); toks jsonb:=coalesce(a#>'{language_graph,tokens}','[]'::jsonb); e jsonb; core jsonb; clauses jsonb; fields jsonb; schemas jsonb; members jsonb; surface_core text; rid_conn uuid; rcode_conn text; rid_schema uuid; rcode_schema text; sidx int; fidx int; st int; en int; fam text; ext_count int:=0; bsum jsonb;
begin
 base:=public.build_subordinate_clause_foundation_v3(p_sentence,p_release_code); clauses:=coalesce(base->'clauses','[]'::jsonb); fields:=coalesce(base->'connector_fields','[]'::jsonb); schemas:=coalesce(base->'schema_models','[]'::jsonb);
 select id,code into rid_conn,rcode_conn from public.grammar_rules where code='nrg_rt_v1.structural.schema.b.connector_field' limit 1; select id,code into rid_schema,rcode_schema from public.grammar_rules where code='nrg_rt_v1.structural.schema.b.subordinate_default' limit 1;
 for e in select x from jsonb_array_elements(coalesce(mwe->'resolved_expressions','[]'::jsonb)) x where x->>'mwe_family'='subordinate_introducer' loop
   core:=e->'clause_core_evidence'; sidx:=nullif(core->>'subject_token_index','')::int; fidx:=nullif(core->>'finite_token_index','')::int; st:=nullif(e->>'start_token_index','')::int; en:=nullif(e->>'end_token_index','')::int;
   if sidx is null or fidx is null or st is null or en is null then continue; end if; if exists(select 1 from jsonb_array_elements(clauses) c where c->>'mwe_expression_id'=e->>'id') then continue; end if; fam:=e->>'function_class';
   select string_agg(x->>'surface',' ' order by nullif(x->>'token_index','')::int) into surface_core from jsonb_array_elements(toks) x where nullif(x->>'token_index','')::int between st and fidx and x->>'token_type'<>'punctuation';
   select coalesce(jsonb_agg(nullif(x->>'token_index','')::int order by nullif(x->>'token_index','')::int),'[]'::jsonb) into members from jsonb_array_elements(toks) x where nullif(x->>'token_index','')::int between st and fidx and x->>'token_type'<>'punctuation';
   fields:=fields||jsonb_build_array(jsonb_build_object('id','scf4:connector:'||st||':'||en,'status','resolved','role','connector_field','field','f','token_index',st,'end_token_index',en,'surface',e->>'surface','effective_lexical_class','multiword_subjunction_connector','classification_source','runtime_multiword_fact_v1','mwe_expression_id',e->>'id','provenance',e->'provenance','rule_id',rid_conn,'rule_code',rcode_conn,'reason_code','resolved_source_verified_multiword_connector_field'));
   schemas:=schemas||jsonb_build_array(jsonb_build_object('id','scf4:schemaB:'||st||':'||sidx||':'||fidx,'status','resolved','schema','B','slot_order',jsonb_build_array('f','a1','n','a2','v','V','N','A'),'connector_token_index',st,'connector_end_token_index',en,'subject_token_index',sidx,'finite_token_index',fidx,'rule_id',rid_schema,'rule_code',rcode_schema,'reason_code','multiword_subjunction_subordinate_schema_b'));
   clauses:=clauses||jsonb_build_array(jsonb_build_object('id','scf4:finite:'||st||':'||sidx||':'||fidx,'status','resolved','clause_type','finite','clause_form','explicit_multiword_subjunction_finite_core','surface',surface_core,'span_start',st,'span_end',fidx,'connector_token_index',st,'connector_end_token_index',en,'connector_surface',e->>'surface','connector_field','f','mwe_expression_id',e->>'id','mwe_code',e->>'mwe_code','mwe_function_class',fam,'subject_token_index',sidx,'subject_surface',core->>'subject_surface','subject_status','explicit','finite_token_index',fidx,'finite_surface',core->>'finite_surface','schema','B','schema_status','resolved_by_multiword_clause_core_evidence','member_token_indices',members,'attachment_state','subordinate_attachment_unresolved','syntactic_function','unresolved','requires_attachment_resolution',true,'provenance',jsonb_build_array(jsonb_build_object('mwe_expression_id',e->>'id','mwe_code',e->>'mwe_code','source',e->'provenance'),jsonb_build_object('rule_id',rid_schema,'rule_code',rcode_schema)))); ext_count:=ext_count+1;
 end loop;
 bsum:=coalesce(base->'summary','{}'::jsonb)||jsonb_build_object('connector_count',coalesce((base#>>'{summary,connector_count}')::int,0)+ext_count,'resolved_clause_count',coalesce((base#>>'{summary,resolved_clause_count}')::int,0)+ext_count,'schema_b_count',coalesce((base#>>'{summary,schema_b_count}')::int,0)+ext_count);
 base:=jsonb_set(base,'{summary}',bsum,true); base:=jsonb_set(base,'{clauses}',clauses,true); base:=jsonb_set(base,'{connector_fields}',fields,true); base:=jsonb_set(base,'{schema_models}',schemas,true);
 return base||jsonb_build_object('version','subordinate-clause-foundation-v4','multiword_extension',jsonb_build_object('resolved_multiword_clause_count',ext_count,'source_graph_runtime_reads',0));
end;
$$;
