create or replace function public.run_multiword_function_expression_golden_v1(p_release_code text default 'runtime-structural-v1.36')
returns jsonb language plpgsql security invoker set search_path='public','pg_catalog' as $$
declare t jsonb:='[]'::jsonb; d jsonb; m jsonb; scf jsonb; scr jsonb; att jsonb; hot jsonb; inh jsonb; finh jsonb; cinh jsonb; minh jsonb; src_hash text; snapshot_hash text; active_nrg int; mcount int; child_rules int; ftd jsonb; sm jsonb; pp jsonb;
begin
 select semantic_hash into snapshot_hash from public.grammar_source_graph_snapshots_v1 order by created_at desc limit 1; src_hash:=public.grammar_source_graph_semantic_hash_v1();
 select count(*) into active_nrg from public.grammar_rules where is_active and code like 'nrg_rt_v1.%';
 select count(*) into mcount from public.grammar_runtime_multiword_facts_v1 f join public.grammar_runtime_releases r on r.id=f.release_id where r.code=p_release_code and f.is_enabled;
 select count(*) into child_rules from public.grammar_runtime_release_rules rr join public.grammar_runtime_releases r on r.id=rr.release_id where r.code=p_release_code and not exists(select 1 from public.grammar_runtime_release_rules pr join public.grammar_runtime_releases p on p.id=pr.release_id where p.code='runtime-structural-v1.35' and pr.rule_id=rr.rule_id);
 t:=t||jsonb_build_array(public.golden_assertion_v1('inventory.total_13',mcount=13,jsonb_build_object('actual',mcount,'expected',13)));
 t:=t||jsonb_build_array(public.golden_assertion_v1('inventory.subordinate_5',(select count(*) from public.grammar_runtime_multiword_facts_v1 f join public.grammar_runtime_releases r on r.id=f.release_id where r.code=p_release_code and f.mwe_family='subordinate_introducer')=5,public.runtime_multiword_inventory_v1(p_release_code,'subordinate_introducer')));
 t:=t||jsonb_build_array(public.golden_assertion_v1('inventory.predicate_8',(select count(*) from public.grammar_runtime_multiword_facts_v1 f join public.grammar_runtime_releases r on r.id=f.release_id where r.code=p_release_code and f.mwe_family='predicate_expression')=8,public.runtime_multiword_inventory_v1(p_release_code,'predicate_expression')));
 d:=public.analyze_text_structural_shadow_v36('Han kommer med mindre det regner.',p_release_code); m:=d#>'{document_graph,sentences,0,analysis,language_graph,multiword_function_expression_v1}'; scf:=d#>'{document_graph,sentences,0,analysis,language_graph,subordinate_clause_foundation_v2}'; scr:=d#>'{document_graph,sentences,0,analysis,language_graph,subordinate_construction_recognition_v1}'; att:=d#>'{document_graph,sentences,0,analysis,language_graph,clause_attachment_function_v1}';
 t:=t||jsonb_build_array(public.golden_assertion_v1('med_mindre.mwe_resolved',m#>>'{summary,resolved_expression_count}'='1' and m#>>'{resolved_expressions,0,mwe_code}'='mwe.subordinate.med_mindre',m));
 t:=t||jsonb_build_array(public.golden_assertion_v1('med_mindre.clause_core_resolved',scf#>>'{multiword_extension,resolved_multiword_clause_count}'='1',scf));
 t:=t||jsonb_build_array(public.golden_assertion_v1('med_mindre.construction_adverbial',exists(select 1 from jsonb_array_elements(scr->'constructions') x where x->>'construction_family'='med_mindre_conditional_adverbial_clause'),scr));
 t:=t||jsonb_build_array(public.golden_assertion_v1('med_mindre.advcl_candidate',exists(select 1 from jsonb_array_elements(att->'candidate_attachments') x where x->>'relation'='advcl'),att));
 d:=public.analyze_text_structural_shadow_v36('Han tar paraply i tilfelle det regner.',p_release_code); m:=d#>'{document_graph,sentences,0,analysis,language_graph,multiword_function_expression_v1}'; scf:=d#>'{document_graph,sentences,0,analysis,language_graph,subordinate_clause_foundation_v2}';
 t:=t||jsonb_build_array(public.golden_assertion_v1('i_tilfelle.finite_clause_resolved',m#>>'{resolved_expressions,0,mwe_code}'='mwe.subordinate.i_tilfelle' and scf#>>'{multiword_extension,resolved_multiword_clause_count}'='1',m));
 d:=public.analyze_text_structural_shadow_v36('Han tar paraply i tilfelle krig.',p_release_code); m:=d#>'{document_graph,sentences,0,analysis,language_graph,multiword_function_expression_v1}'; scf:=d#>'{document_graph,sentences,0,analysis,language_graph,subordinate_clause_foundation_v2}';
 t:=t||jsonb_build_array(public.golden_assertion_v1('i_tilfelle.np_not_clause',m#>>'{summary,resolved_expression_count}'='0' and scf#>>'{multiword_extension,resolved_multiword_clause_count}'='0',m));
 d:=public.analyze_text_structural_shadow_v36('Han tar paraply i fall det regner.',p_release_code); m:=d#>'{document_graph,sentences,0,analysis,language_graph,multiword_function_expression_v1}';
 t:=t||jsonb_build_array(public.golden_assertion_v1('i_fall.finite_clause_resolved',exists(select 1 from jsonb_array_elements(m->'resolved_expressions') x where x->>'mwe_code'='mwe.subordinate.i_fall'),m));
 d:=public.analyze_text_structural_shadow_v36('Han dro for at han skulle hjelpe.',p_release_code); m:=d#>'{document_graph,sentences,0,analysis,language_graph,multiword_function_expression_v1}';
 t:=t||jsonb_build_array(public.golden_assertion_v1('for_at.candidate_not_resolved',m#>>'{summary,candidate_expression_count}'='1' and m#>>'{summary,resolved_expression_count}'='0' and m#>>'{candidate_expressions,0,mwe_code}'='mwe.subordinate.for_at',m));
 d:=public.analyze_text_structural_shadow_v36('Han jobbet slik at alt ble ferdig.',p_release_code); m:=d#>'{document_graph,sentences,0,analysis,language_graph,multiword_function_expression_v1}';
 t:=t||jsonb_build_array(public.golden_assertion_v1('slik_at.candidate_not_resolved',m#>>'{summary,candidate_expression_count}'='1' and m#>>'{summary,resolved_expression_count}'='0' and m#>>'{candidate_expressions,0,mwe_code}'='mwe.subordinate.slik_at',m));
 d:=public.analyze_text_structural_shadow_v36('Han passer på at hun kommer.',p_release_code); m:=d#>'{document_graph,sentences,0,analysis,language_graph,multiword_function_expression_v1}';
 t:=t||jsonb_build_array(public.golden_assertion_v1('predicate.passe_paa.sequence_identity',m#>>'{candidate_expressions,0,mwe_code}'='mwe.predicate.passe_på' and m#>>'{candidate_expressions,0,sequence_identity}'='resolved',m));
 d:=public.analyze_text_structural_shadow_v36('Han finner ut at hun kommer.',p_release_code); m:=d#>'{document_graph,sentences,0,analysis,language_graph,multiword_function_expression_v1}';
 t:=t||jsonb_build_array(public.golden_assertion_v1('predicate.finne_ut.sense_blocked',m#>>'{candidate_expressions,0,mwe_code}'='mwe.predicate.finne_ut' and m#>>'{candidate_expressions,0,required_capability}'='predicate_sense_resolution',m));
 d:=public.analyze_text_structural_shadow_v36('Han tror på at hun kommer.',p_release_code); m:=d#>'{document_graph,sentences,0,analysis,language_graph,multiword_function_expression_v1}';
 t:=t||jsonb_build_array(public.golden_assertion_v1('predicate.tru_paa.no_cross_standard_guess',m#>>'{summary,matched_occurrence_count}'='0',m));
 d:=public.analyze_text_structural_shadow_v36('Han reiser ikke.',p_release_code); m:=d#>'{document_graph,sentences,0,analysis,language_graph,multiword_function_expression_v1}';
 t:=t||jsonb_build_array(public.golden_assertion_v1('ordinary.no_mwe',m#>>'{summary,matched_occurrence_count}'='0',m)); t:=t||jsonb_build_array(public.golden_assertion_v1('safety.no_learner_error',m#>>'{summary,learner_error_claims}'='0',m));
 hot:=public.runtime_hot_path_isolation_audit_v1('analyze_text_structural_shadow_v36',64); t:=t||jsonb_build_array(public.golden_assertion_v1('architecture.hot_path_isolated',coalesce((hot->>'pass')::boolean,false),hot));
 inh:=public.validate_runtime_child_release_inheritance_v1(p_release_code,'runtime-structural-v1.35'); t:=t||jsonb_build_array(public.golden_assertion_v1('architecture.rule_inheritance',coalesce((inh->>'valid')::boolean,false),inh));
 finh:=public.validate_runtime_materialized_fact_inheritance_v1(p_release_code,'runtime-structural-v1.35'); t:=t||jsonb_build_array(public.golden_assertion_v1('architecture.materialized_fact_inheritance',coalesce((finh->>'valid')::boolean,false),finh));
 cinh:=public.validate_runtime_constraint_fact_inheritance_v1(p_release_code,'runtime-structural-v1.35'); t:=t||jsonb_build_array(public.golden_assertion_v1('architecture.constraint_inheritance',coalesce((cinh->>'valid')::boolean,false),cinh));
 minh:=public.validate_runtime_multiword_fact_inheritance_v1(p_release_code,'runtime-structural-v1.35'); t:=t||jsonb_build_array(public.golden_assertion_v1('architecture.multiword_parent_preserved',coalesce((minh->>'valid')::boolean,false),minh));
 t:=t||jsonb_build_array(public.golden_assertion_v1('architecture.child_only_rules_zero',child_rules=0,jsonb_build_object('child_only_rules',child_rules))); t:=t||jsonb_build_array(public.golden_assertion_v1('architecture.global_nrg_active_zero',active_nrg=0,jsonb_build_object('active_nrg',active_nrg)));
 t:=t||jsonb_build_array(public.golden_assertion_v1('source_graph.hash_unchanged',src_hash=snapshot_hash,jsonb_build_object('current_hash',src_hash,'snapshot_hash',snapshot_hash)));
 t:=t||jsonb_build_array(public.golden_assertion_v1('immutable.tokenize_simple',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='tokenize_text_simple' and md5(pg_get_functiondef(p.oid))='40819fa48cc6e48372cbf42275f2bb0c'),'{}'::jsonb));
 t:=t||jsonb_build_array(public.golden_assertion_v1('immutable.structural_core',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='analyze_text_structural_shadow_core_v1' and md5(pg_get_functiondef(p.oid))='b15193a826907ea6082a1aae52f15fec'),'{}'::jsonb));
 t:=t||jsonb_build_array(public.golden_assertion_v1('immutable.tokenize_v2',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='tokenize_text_v2' and md5(pg_get_functiondef(p.oid))='f76f85eee4469e74079a101da442ec52'),'{}'::jsonb));
 ftd:=public.run_forms_tenses_degrees_golden_v1(p_release_code); t:=t||jsonb_build_array(public.golden_assertion_v1('regression.forms_tenses_degrees',coalesce((ftd->>'failed')::int,999)=0 and coalesce((ftd->>'passed')::int,0)=52,ftd)); sm:=public.run_sentence_model_golden_v2(p_release_code); t:=t||jsonb_build_array(public.golden_assertion_v1('regression.sentence_model',coalesce((sm->>'failed')::int,999)=0 and coalesce((sm->>'passed')::int,0)=36,sm)); pp:=public.run_pedagogical_projection_golden_v1(p_release_code); t:=t||jsonb_build_array(public.golden_assertion_v1('regression.pedagogy',coalesce((pp->>'failed')::int,999)=0 and coalesce((pp->>'passed')::int,0)=36,pp));
 return jsonb_build_object('version','multiword-function-expression-golden-v1','release_code',p_release_code,'tests',t,'total',jsonb_array_length(t),'passed',(select count(*) from jsonb_array_elements(t) x where coalesce((x->>'passed')::boolean,false)),'failed',(select count(*) from jsonb_array_elements(t) x where not coalesce((x->>'passed')::boolean,false)),'failures',(select coalesce(jsonb_agg(x),'[]'::jsonb) from jsonb_array_elements(t) x where not coalesce((x->>'passed')::boolean,false)));
end;
$$;

create or replace function public.run_multiword_function_expression_shadow_comparator_v1(p_release_code text default 'runtime-structural-v1.36',p_parent_release_code text default 'runtime-structural-v1.35',p_corpus_version text default 'shadow-corpus-v2.0')
returns uuid language plpgsql security invoker set search_path='public','pg_catalog' as $$
declare child_id uuid; child_status text; parent_status text; expected int; batch uuid; c record; pd jsonb; cd jsonb; pa jsonb; ca jsonb; pp jsonb; cp jsonb; cmp jsonb;
begin
 select id,status into child_id,child_status from public.grammar_runtime_releases where code=p_release_code; select status into parent_status from public.grammar_runtime_releases where code=p_parent_release_code;
 if child_status not in ('golden','shadow') then raise exception 'Child must be golden/shadow'; end if; if parent_status<>'shadow' then raise exception 'Parent must be shadow'; end if;
 select count(*)::int into expected from public.grammar_shadow_v2_corpus_cases where corpus_version=p_corpus_version and is_active; if expected<>34 then raise exception 'Expected 34 corpus cases, got %',expected; end if;
 insert into public.grammar_shadow_v2_batches(runtime_release_id,corpus_version,baseline_name,baseline_version,shadow_engine_version,active_legacy_rule_checksum,status,expected_cases,metadata,started_at)
 values(child_id,p_corpus_version,p_parent_release_code,'grammar-structural-shadow-v35','grammar-structural-shadow-v36',public.grammar_shadow_v2_legacy_rule_checksum(),'running',expected,jsonb_build_object('comparison_mode','parent_child_multiword_function_expression_v1','parent_release',p_parent_release_code,'child_release',p_release_code,'single_capability','Multiword Function Expression Resolution V1'),clock_timestamp()) returning id into batch;
 for c in select id,code,input_text from public.grammar_shadow_v2_corpus_cases where corpus_version=p_corpus_version and is_active order by code loop begin
   pd:=public.analyze_text_structural_shadow_v35(c.input_text,p_parent_release_code); cd:=public.analyze_text_structural_shadow_v36(c.input_text,p_release_code); pa:=coalesce(pd#>'{document_graph,sentences,0,analysis}','{}'::jsonb); ca:=coalesce(cd#>'{document_graph,sentences,0,analysis}','{}'::jsonb); pp:=public.project_structural_grammar_shadow_v2(pa); cp:=public.project_structural_grammar_shadow_v2(ca); cmp:=public.compare_grammar_shadow_v2(pp,cp);
   insert into public.grammar_shadow_v2_comparisons(batch_id,case_id,case_code,input_text,execution_status,classification,labels,baseline_result,shadow_result,baseline_projection,shadow_projection,comparison,baseline_version,shadow_version) values(batch,c.id,c.code,c.input_text,'completed',cmp->>'classification',coalesce(cmp->'labels','[]'::jsonb),pa,ca,pp,cp,cmp,'grammar-structural-shadow-v35','grammar-structural-shadow-v36');
  exception when others then insert into public.grammar_shadow_v2_comparisons(batch_id,case_id,case_code,input_text,execution_status,classification,labels,baseline_result,shadow_result,baseline_projection,shadow_projection,comparison,baseline_version,shadow_version,error_message) values(batch,c.id,c.code,c.input_text,'error',null,'[]','{}','{}','{}','{}','{}','grammar-structural-shadow-v35','grammar-structural-shadow-v36',sqlerrm); end; end loop;
 perform public.finalize_grammar_shadow_v2_batch(batch); return batch;
end;
$$;
