create or replace view public.trusted_expressions_v1 as
select
  e.id,
  e.lemma,
  e.display_form,
  e.normalized_key,
  e.language,
  e.pos,
  e.expression_subtype,
  e.translation_ua,
  e.translation_en,
  e.example,
  e.notes_ua,
  e.cefr,
  e.frequency_level,
  e.frequency_rank,
  e.importance_score,
  e.source_naob,
  e.source_wiktionary,
  e.source_gemini,
  e.source_ordbokene,
  e.source_manual,
  e.source_urls,
  e.raw_sources,
  e.verification,
  e.confidence,
  e.lexeme_id,
  e.topic,
  e.source_verified,
  e.verification_status,
  e.linguistic_evidence,
  e.verification_tier,
  e.verification_evidence,
  se.review_status,
  se.semantic_confidence,
  se.learning_confidence,
  se.verification_confidence,
  se.source_confidence,
  se.form_confidence,
  se.conflicts,
  se.audit_notes,
  se.evidence as semantic_audit_evidence,
  e.created_at,
  e.updated_at
from public.expression_catalog e
join public.expression_semantic_enrichment se
  on se.expression_id = e.id
where se.review_status = 'trusted';