import { writeFileSync } from 'fs';

const wiktionary = [
  {lemma:"å bite i det sure eplet",expression_subtype:"idiom",meaning_en:"to bite the bullet"},
  {lemma:"å gå rundt grøten",expression_subtype:"idiom",meaning_en:"to beat around the bush"},
  {lemma:"å ha is i magen",expression_subtype:"idiom",meaning_en:"to stay calm, have patience"},
  {lemma:"å slå to fluer i én smekk",expression_subtype:"idiom",meaning_en:"to kill two birds with one stone"},
  {lemma:"å ta saken i egne hender",expression_subtype:"idiom",meaning_en:"to take matters into one's own hands"},
  {lemma:"å treffe spikeren på hodet",expression_subtype:"idiom",meaning_en:"to hit the nail on the head"},
  {lemma:"å være i samme båt",expression_subtype:"idiom",meaning_en:"to be in the same boat"},
  {lemma:"å stå på egne ben",expression_subtype:"idiom",meaning_en:"to stand on one's own feet"},
  {lemma:"å holde hodet over vannet",expression_subtype:"idiom",meaning_en:"to keep one's head above water"},
  {lemma:"å brenne alle broer",expression_subtype:"idiom",meaning_en:"to burn all bridges"},
  {lemma:"å kaste perler for svin",expression_subtype:"idiom",meaning_en:"to cast pearls before swine"},
  {lemma:"å ha mange jern i ilden",expression_subtype:"idiom",meaning_en:"to have many irons in the fire"},
  {lemma:"å se skogen for bare trær",expression_subtype:"idiom",meaning_en:"to not see the forest for the trees"},
  {lemma:"å komme til poenget",expression_subtype:"fixed_expression",meaning_en:"to get to the point"},
  {lemma:"å ta det med ro",expression_subtype:"fixed_expression",meaning_en:"to take it easy"},
  {lemma:"å glede seg",expression_subtype:"lexical_reflexive",meaning_en:"to be happy, to look forward"},
  {lemma:"å glede seg til",expression_subtype:"reflexive_construction",meaning_en:"to look forward to"},
  {lemma:"å kose seg",expression_subtype:"lexical_reflexive",meaning_en:"to enjoy oneself"},
  {lemma:"å finne seg i",expression_subtype:"lexical_reflexive",meaning_en:"to put up with"},
  {lemma:"å bestemme seg for",expression_subtype:"lexical_reflexive",meaning_en:"to decide on"},
  {lemma:"å skynde seg",expression_subtype:"lexical_reflexive",meaning_en:"to hurry"},
  {lemma:"å kle på seg",expression_subtype:"reflexive_particle_verb",meaning_en:"to get dressed"},
  {lemma:"å kle av seg",expression_subtype:"reflexive_particle_verb",meaning_en:"to undress"},
  {lemma:"å gi opp",expression_subtype:"particle_verb",meaning_en:"to give up"},
  {lemma:"å ta av",expression_subtype:"particle_verb",meaning_en:"to take off"},
  {lemma:"å sette opp",expression_subtype:"particle_verb",meaning_en:"to set up"},
  {lemma:"å legge merke til",expression_subtype:"particle_verb",meaning_en:"to notice"},
  {lemma:"å holde på med",expression_subtype:"particle_verb",meaning_en:"to be busy with"},
  {lemma:"å se frem til",expression_subtype:"particle_verb",meaning_en:"to look forward to"},
  {lemma:"å delta i",expression_subtype:"prepositional_verb",meaning_en:"to participate in"},
  {lemma:"å tro på",expression_subtype:"prepositional_verb",meaning_en:"to believe in"},
  {lemma:"å stole på",expression_subtype:"prepositional_verb",meaning_en:"to trust"},
  {lemma:"å tenke på",expression_subtype:"prepositional_verb",meaning_en:"to think about"},
  {lemma:"å snakke om",expression_subtype:"prepositional_verb",meaning_en:"to talk about"},
  {lemma:"i det siste",expression_subtype:"time_expression",meaning_en:"lately, recently"},
  {lemma:"av og til",expression_subtype:"time_expression",meaning_en:"from time to time"},
  {lemma:"til slutt",expression_subtype:"time_expression",meaning_en:"in the end, finally"},
  {lemma:"til å begynne med",expression_subtype:"time_expression",meaning_en:"to begin with"},
  {lemma:"for øyeblikket",expression_subtype:"time_expression",meaning_en:"at the moment"},
  {lemma:"ikke i det hele tatt",expression_subtype:"fixed_expression",meaning_en:"not at all"},
  {lemma:"i alle fall",expression_subtype:"fixed_expression",meaning_en:"in any case"},
  {lemma:"på den ene siden",expression_subtype:"discourse_marker",meaning_en:"on the one hand"},
  {lemma:"på den andre siden",expression_subtype:"discourse_marker",meaning_en:"on the other hand"},
  {lemma:"med andre ord",expression_subtype:"discourse_marker",meaning_en:"in other words"},
  {lemma:"for øvrig",expression_subtype:"discourse_marker",meaning_en:"by the way, moreover"},
  {lemma:"ha det bra",expression_subtype:"social_formula",meaning_en:"take care, goodbye"},
  {lemma:"lykke til",expression_subtype:"social_formula",meaning_en:"good luck"},
  {lemma:"mange takk",expression_subtype:"social_formula",meaning_en:"many thanks"},
  {lemma:"ingen årsak",expression_subtype:"social_formula",meaning_en:"you're welcome"},
  {lemma:"god bedring",expression_subtype:"social_formula",meaning_en:"get well soon"},
];

const naob = [
  {lemma:"å ha det travelt",source_word:"ha",meaning_en:"to be busy"},
  {lemma:"å ha det bra",source_word:"ha",meaning_en:"to be doing well"},
  {lemma:"å ha råd til",source_word:"ha",meaning_en:"to afford"},
  {lemma:"å ha lyst til",source_word:"ha",meaning_en:"to feel like, to want to"},
  {lemma:"å ha rett",source_word:"ha",meaning_en:"to be right"},
  {lemma:"å ha noe på hjertet",source_word:"ha",meaning_en:"to have something on one's mind"},
  {lemma:"å ta vare på",source_word:"ta",meaning_en:"to take care of"},
  {lemma:"å ta seg av",source_word:"ta",meaning_en:"to look after"},
  {lemma:"å ta feil",source_word:"ta",meaning_en:"to be wrong"},
  {lemma:"å ta kontakt med",source_word:"ta",meaning_en:"to contact"},
  {lemma:"å ta ansvar for",source_word:"ta",meaning_en:"to take responsibility for"},
  {lemma:"å ta hensyn til",source_word:"ta",meaning_en:"to take into consideration"},
  {lemma:"å ta det med ro",source_word:"ta",meaning_en:"to take it easy"},
  {lemma:"å ta seg sammen",source_word:"ta",meaning_en:"to pull oneself together"},
  {lemma:"å gå glipp av",source_word:"gå",meaning_en:"to miss out on"},
  {lemma:"å gå ut fra",source_word:"gå",meaning_en:"to assume"},
  {lemma:"å gå i gang med",source_word:"gå",meaning_en:"to get started with"},
  {lemma:"å komme i gang",source_word:"komme",meaning_en:"to get going"},
  {lemma:"å komme over",source_word:"komme",meaning_en:"to get over"},
  {lemma:"å komme opp med",source_word:"komme",meaning_en:"to come up with"},
  {lemma:"å bli kjent med",source_word:"bli",meaning_en:"to get to know"},
  {lemma:"å bli enig om",source_word:"bli",meaning_en:"to agree on"},
  {lemma:"å bli ferdig med",source_word:"bli",meaning_en:"to finish"},
  {lemma:"å sette pris på",source_word:"sette",meaning_en:"to appreciate"},
  {lemma:"å sette i gang",source_word:"sette",meaning_en:"to start, set in motion"},
  {lemma:"å legge vekt på",source_word:"legge",meaning_en:"to emphasise"},
  {lemma:"å legge til rette for",source_word:"legge",meaning_en:"to facilitate"},
  {lemma:"å se etter",source_word:"se",meaning_en:"to look for"},
  {lemma:"å se opp til",source_word:"se",meaning_en:"to look up to"},
  {lemma:"å si fra",source_word:"si",meaning_en:"to speak up"},
  {lemma:"å gi uttrykk for",source_word:"gi",meaning_en:"to express"},
  {lemma:"å holde seg til",source_word:"holde",meaning_en:"to stick to"},
  {lemma:"å holde kontakten",source_word:"holde",meaning_en:"to stay in touch"},
  {lemma:"å finne ut av",source_word:"finne",meaning_en:"to figure out"},
  {lemma:"å finne sted",source_word:"finne",meaning_en:"to take place"},
  {lemma:"å klare seg",source_word:"klare",meaning_en:"to manage, get by"},
  {lemma:"å interessere seg for",source_word:"interessere",meaning_en:"to be interested in"},
  {lemma:"å bry seg om",source_word:"bry",meaning_en:"to care about"},
  {lemma:"å bekymre seg for",source_word:"bekymre",meaning_en:"to worry about"},
  {lemma:"å dra nytte av",source_word:"nytte",meaning_en:"to benefit from"},
];

writeFileSync('./wiktionary_expressions.json', JSON.stringify(wiktionary, null, 2));
writeFileSync('./naob_expressions.json', JSON.stringify(naob, null, 2));
console.log('wiktionary:', wiktionary.length, 'entries');
console.log('naob:', naob.length, 'entries');
