UPDATE lexemes SET topic = 'health_emotions' WHERE lemma ILIKE 'angre på' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'numbers_time' WHERE lemma ILIKE 'annenhver' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'numbers_time' WHERE lemma ILIKE 'avtalt tid' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'reflexive_verbs' WHERE lemma ILIKE 'bestemme seg for noe' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'discourse' WHERE lemma ILIKE 'blant annet / andre' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'social_phrases' WHERE lemma ILIKE 'bli kjent med' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'reflexive_verbs' WHERE lemma ILIKE 'bli vant til / å være vant til' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'discourse' WHERE lemma ILIKE 'det er ingen tvil om' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'degree_quantity' WHERE lemma ILIKE 'det lille ekstra' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'discourse' WHERE lemma ILIKE 'det ser du vel' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'communication' WHERE lemma ILIKE 'det stemmer' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'communication' WHERE lemma ILIKE 'du har rett (i det)' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'reflexive_verbs' WHERE lemma ILIKE 'engasjere seg' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'discourse' WHERE lemma ILIKE 'er ikke det.. (du)' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'time_expressions' WHERE lemma ILIKE 'etter en stund' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'family_home' WHERE lemma ILIKE 'få (ha) barn med' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'general' WHERE lemma ILIKE 'få lov til å' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'politics_society' WHERE lemma ILIKE 'felles verdier' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'core_verbs' WHERE lemma ILIKE 'finne ut' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'health_emotions' WHERE lemma ILIKE 'føle seg fri' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'time_expressions' WHERE lemma ILIKE 'for dager- timer- måneder- år- siden' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'time_expressions' WHERE lemma ILIKE 'for lenge siden' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'time_expressions' WHERE lemma ILIKE 'for sent' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'time_expressions' WHERE lemma ILIKE 'for tidlig' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'time_expressions' WHERE lemma ILIKE 'forrige dag / uke / måned / år' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'movement_travel' WHERE lemma ILIKE 'forsinket' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'general' WHERE lemma ILIKE 'gå glipp av' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'movement_travel' WHERE lemma ILIKE 'gå over' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'communication' WHERE lemma ILIKE 'gi beskjed' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'core_verbs' WHERE lemma ILIKE 'gi fra seg' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'reflexive_verbs' WHERE lemma ILIKE 'glede seg' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'reflexive_verbs' WHERE lemma ILIKE 'glede seg til' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'reflexive_verbs' WHERE lemma ILIKE 'grue seg' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'social_phrases' WHERE lemma ILIKE 'ha mye til felles' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'movement_travel' WHERE lemma ILIKE 'hit og dit' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'communication' WHERE lemma ILIKE 'holde (en) tale' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'core_verbs' WHERE lemma ILIKE 'holde på' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'family_home' WHERE lemma ILIKE 'holde rent' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'communication' WHERE lemma ILIKE 'høres ut som' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'work_business' WHERE lemma ILIKE 'hva driver du med?' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'social_phrases' WHERE lemma ILIKE 'hva med deg?' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'general' WHERE lemma ILIKE 'hva slags' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'general' WHERE lemma ILIKE 'hvem som helst' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'general' WHERE lemma ILIKE 'hvor som helst' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'health_emotions' WHERE lemma ILIKE 'hvordan er det med deg?' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'social_phrases' WHERE lemma ILIKE 'hvordan går det?' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'health_emotions' WHERE lemma ILIKE 'hvordan har du det?' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'time_expressions' WHERE lemma ILIKE 'i år' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'discourse' WHERE lemma ILIKE 'i begynnelsen var' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'time_expressions' WHERE lemma ILIKE 'i dag' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'politics_society' WHERE lemma ILIKE 'i dagens samfunn' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'general' WHERE lemma ILIKE 'i det hele tatt' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'time_expressions' WHERE lemma ILIKE 'i det siste, den siste uka, de siste årene' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'time_expressions' WHERE lemma ILIKE 'i forfjor' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'time_expressions' WHERE lemma ILIKE 'i forgårs' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'time_expressions' WHERE lemma ILIKE 'i går' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'degree_quantity' WHERE lemma ILIKE 'i like stor grad' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'time_expressions' WHERE lemma ILIKE 'i løpet av dagen, en time, en dag, en måned, et år' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'time_expressions' WHERE lemma ILIKE 'i morgen' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'degree_quantity' WHERE lemma ILIKE 'i nærheten av' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'time_expressions' WHERE lemma ILIKE 'i slutten av uka / måneden' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'discourse' WHERE lemma ILIKE 'i tillegg (til)' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'health_emotions' WHERE lemma ILIKE 'jeg gleder meg' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'nature_weather' WHERE lemma ILIKE 'kaldt / varmt / fuktig i lufta' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'idioms' WHERE lemma ILIKE 'kaste kortene' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'reflexive_verbs' WHERE lemma ILIKE 'kjede seg' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'health_emotions' WHERE lemma ILIKE 'kjenne på' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'general' WHERE lemma ILIKE 'klare seg selv' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'general' WHERE lemma ILIKE 'kle av' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'general' WHERE lemma ILIKE 'kle på' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'reflexive_verbs' WHERE lemma ILIKE 'kle på seg' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'movement_travel' WHERE lemma ILIKE 'komme nærmere / nærme seg land' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'social_phrases' WHERE lemma ILIKE 'komme på besøk' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'social_phrases' WHERE lemma ILIKE 'komme på døra' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'social_phrases' WHERE lemma ILIKE 'la noen være i fred' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'education' WHERE lemma ILIKE 'lære bort' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'communication' WHERE lemma ILIKE 'legge merke til' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'work_business' WHERE lemma ILIKE 'leve av' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'degree_quantity' WHERE lemma ILIKE 'like ofte som før' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'work_business' WHERE lemma ILIKE 'lønnet arbeid' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'degree_quantity' WHERE lemma ILIKE 'minst mulig' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'reflexive_verbs' WHERE lemma ILIKE 'more seg' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'movement_travel' WHERE lemma ILIKE 'nærme seg' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'discourse' WHERE lemma ILIKE 'når det gjelder' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'time_expressions' WHERE lemma ILIKE 'når som helst' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'time_expressions' WHERE lemma ILIKE 'neste dag / uke / måned / år' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'time_expressions' WHERE lemma ILIKE 'om 5 minutter, om en uke, om en måned, om et år' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'time_expressions' WHERE lemma ILIKE 'om dagen' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'degree_quantity' WHERE lemma ILIKE 'om gangen' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'reflexive_verbs' WHERE lemma ILIKE 'oppføre seg' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'numbers_time' WHERE lemma ILIKE 'overimorgen' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'movement_travel' WHERE lemma ILIKE 'på bakken' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'idioms' WHERE lemma ILIKE 'på egen hånd' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'work_business' WHERE lemma ILIKE 'på full tid' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'family_home' WHERE lemma ILIKE 'på landet' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'core_verbs' WHERE lemma ILIKE 'passe på' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'core_verbs' WHERE lemma ILIKE 'pleier å' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'family_home' WHERE lemma ILIKE 're opp' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'reflexive_verbs' WHERE lemma ILIKE 'reise seg' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'social_phrases' WHERE lemma ILIKE 'så godt å høre' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'core_verbs' WHERE lemma ILIKE 'se på' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'movement_travel' WHERE lemma ILIKE 'sette seg ned' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'communication' WHERE lemma ILIKE 'si ifra' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'time_expressions' WHERE lemma ILIKE 'siden den gang' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'core_verbs' WHERE lemma ILIKE 'skje med' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'reflexive_verbs' WHERE lemma ILIKE 'skynde seg' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'core_verbs' WHERE lemma ILIKE 'slutte med' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'communication' WHERE lemma ILIKE 'snakke med hverandre' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'movement_travel' WHERE lemma ILIKE 'stå opp' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'idioms' WHERE lemma ILIKE 'ta det rolig' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'core_verbs' WHERE lemma ILIKE 'ta opp igjen' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'core_verbs' WHERE lemma ILIKE 'tenke på' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'health_emotions' WHERE lemma ILIKE 'trives med' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'core_verbs' WHERE lemma ILIKE 'tro på' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'reflexive_verbs' WHERE lemma ILIKE 'vaske seg' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'communication' WHERE lemma ILIKE 'vente på svar' AND pos = 'expression' AND topic IS NULL;
UPDATE lexemes SET topic = 'reflexive_verbs' WHERE lemma ILIKE 'vise seg' AND pos = 'expression' AND topic IS NULL;