import type {
  LectureMarkerType,
  LectureSourceLanguage,
} from '@/features/audio/lectureTypes';

export type AudioUiLanguage =
  | 'ua'
  | 'en'
  | 'no';

export function normalizeAudioUiLanguage(
  value: string | null | undefined
): AudioUiLanguage {
  const language = String(value || '')
    .trim()
    .toLowerCase();

  if (
    language === 'no' ||
    language === 'nb'
  ) {
    return 'no';
  }

  if (language === 'en') {
    return 'en';
  }

  return 'ua';
}

const COPY = {
  ua: {
    captureTitle: '🎙 Запис аудіо',
    startRecording: 'Почати запис',
    idleInfo: 'Запишіть лекцію локально у M4A або імпортуйте готовий аудіофайл. Звичайний запис працює у фоновому режимі та під час блокування iPhone.',
    stopRecording: 'Зупинити запис',
    preparingLive: 'Підготовка Live…',
    live: 'Live',
    stopLive: 'Зупинити Live',
    liveTitle: 'Live транскрипція',
    livePreparing: 'Готуємо локальну модель…',
    liveListening: 'Слухаю та розпізнаю…',
    liveFinalizing: 'Зберігаємо та фіналізуємо…',
    liveSource: 'Оригінал',
    liveTranslation: 'Переклад',
    liveWaiting: 'Очікую на мовлення…',
    liveSaved: 'Live запис збережено',
    liveError: 'Помилка Live',
    close: 'Закрити',
    importAudio: 'Імпортувати аудіо',
    supportedFormats: 'M4A, MP3, WAV, AAC, CAF або MP4',
    savedLectures: 'Збережені записи',
    savedRecording: 'Збережений запис',
    emptyLibrary: 'Збережені записи з’являться тут.',
    processing: 'Обробка…',
    processingInProgress: 'Триває обробка',
    waitForProcessing: 'Зачекайте, поки завершиться транскрипція або переклад.',
    waitForProcessingBeforeImport: 'Зачекайте, поки завершиться транскрипція або переклад, перш ніж імпортувати інший аудіофайл.',
    microphonePermission: 'Доступ до мікрофона',
    microphoneRequired: 'Для запису потрібен доступ до мікрофона.',
    recordingError: 'Помилка запису',
    recordingNotSaved: 'Запис не збережено',
    activeRecordingMissing: 'Активний аудіозапис не знайдено.',
    recordingTooShort: 'Запис надто короткий.',
    nativeRecordingInvalid: 'Файл запису пошкоджений або неповний.',
    unexpectedAudioPath: 'Не вдалося завершити аудіозапис належним чином.',
    audioImported: 'Аудіо імпортовано',
    importFailed: 'Не вдалося імпортувати',
    noAudioSelected: 'Аудіофайл не вибрано.',
    unsupportedAudioFormat: 'Непідтримуваний формат аудіо. Використовуйте M4A, MP3, WAV, AAC, CAF або MP4.',
    selectedAudioInvalid: 'Вибраний аудіофайл відсутній або пошкоджений.',
    selectedAudioNoDuration: 'Не вдалося визначити тривалість вибраного аудіофайлу.',
    importedAudioInvalid: 'Не вдалося створити коректну копію імпортованого аудіофайлу.',
    transcriptError: 'Помилка транскрипту',
    transcriptOpenFailed: 'Не вдалося відкрити транскрипт.',
    renameLecture: 'Перейменувати запис',
    renamePrompt: 'Введіть назву запису. Залиште поле порожнім, щоб знову використовувати дату.',
    cancel: 'Скасувати',
    save: 'Зберегти',
    renameError: 'Помилка перейменування',
    renameSaveFailed: 'Не вдалося зберегти назву запису.',
    deleteLecture: 'Видалити запис?',
    deletePrompt: 'Аудіозапис і транскрипт буде назавжди видалено з цього iPhone.',
    delete: 'Видалити',
    deleteError: 'Помилка видалення',
    deleteFailed: 'Не вдалося видалити запис.',
    useNorwegian: 'Використовувати норвезьку для цього запису',
    useEnglish: 'Використовувати англійську для цього запису',
    pausedForCall: '⏸ ПАУЗА НА ЧАС ДЗВІНКА',
    recording: '● ЗАПИС',
    callPauseInfo: '📞 Запис безпечно призупинено на час дзвінка. Після завершення дзвінка він відновиться автоматично.',
    microphoneLevel: 'Рівень мікрофона',
    microphoneNoSound: '⚠ Мікрофон не отримує звук',
    microphoneQuiet: 'Сигнал тихий · за можливості піднесіть iPhone ближче',
    lockRecordingInfo: 'Запис продовжується, навіть коли iPhone заблоковано.',
    audioSaved: '✓ Аудіо збережено локально як M4A',
    readyForLaterTranscription: 'Готово до подальшої транскрипції.',
    markThisMoment: 'Позначити цей момент',
    markerImportant: '⭐ Важливо',
    markerUnclear: '❓ Незрозуміло',
    markerRepeat: '🔁 Повторити',
    markerTerm: '🆕 Термін',
    markMoment: '⭐ Позначити момент',
    markersSaved: 'Збережено позначок:',
    interrupted: '⚠ Запис було перервано',
    audioSavedShort: 'Аудіо збережено',
    renameAccessibility: 'Перейменувати запис',
    deleteAccessibility: 'Видалити запис',
    loadingAudio: 'Завантаження аудіо…',
    back15: 'Назад на 15 секунд',
    forward15: 'Вперед на 15 секунд',
    back15Short: '↶ 15 с',
    forward15Short: '15 с ↷',
    cannotPlayInterrupted: 'Перерваний запис неможливо відтворити',
    pauseLecture: 'Призупинити відтворення',
    playLecture: 'Відтворити запис',
    noPlayback: '⚠ Немає відтворення',
    loading: '… Завантаження',
    pause: '⏸ Пауза',
    play: '▶ Відтворити',
    cannotTranscribeInterrupted: 'Перерваний запис неможливо транскрибувати',
    hideTranscript: 'Сховати транскрипт',
    openTranscript: 'Відкрити транскрипт',
    createTranscriptAccessibility: 'Створити транскрипт',
    noTranscript: '⚠ Немає транскрипту',
    hideText: '📄 Сховати текст',
    transcript: '📄 Транскрипт',
    transcribing: '… Транскрибування',
    createTranscript: 'Створити транскрипт',
    closeExportMenu: 'Закрити меню експорту',
    shareOrExport: 'Поділитися або експортувати запис',
    exporting: '… Експорт',
    export: '✕ Експорт',
    shareExport: '↗ Поділитися / Експорт',
    playback: 'Відтворення',
    interruptedDescription: 'Запис було перервано до того, як iOS встиг завершити M4A-файл. Відтворення та транскрипція недоступні. Файл можна зберегти/експортувати для відновлення або видалити.',
    preparingWhisper: 'Підготовка офлайн-моделі Whisper…',
    modelReady: 'Модель готова',
    noTextRetrying: 'Текст не знайдено · повторна спроба…',
    transcribingLocally: 'Транскрибування локально на цьому iPhone…',
    transcriptNotStarted: 'Транскрипцію не розпочато · WhisperKit офлайн',
    readyForTranscription: 'Готово до локальної транскрипції',
    transcriptionInterrupted: 'Транскрипцію перервано · натисніть «Створити транскрипт», щоб повторити',
    transcriptReady: 'Транскрипт готовий',
    transcriptionFailedStatus: 'Помилка транскрипції · натисніть «Створити транскрипт», щоб повторити',
    onDevice: 'на пристрої',
    retranscribingPreparing: 'Повторна транскрипція… готуємо офлайн-модель Whisper. Поточний транскрипт залишиться видимим, доки нова версія не буде готова.',
    retranscribingRetrying: 'Повторна транскрипція… під час першої спроби текст не знайдено, повторюємо ще раз.',
    retranscribingLocal: 'Повторна транскрипція локально на цьому iPhone… Поточний транскрипт залишиться видимим до завершення заміни.',
    firstUseWhisper: 'Під час першого використання може завантажуватися модель Whisper. Залиште застосунок відкритим і підключеним до інтернету.',
    processingLocally: 'Обробка відбувається локально. Довгі записи можуть оброблятися кілька хвилин.',
    transcriptUpdated: '✓ Транскрипт оновлено',
    updatedJustNow: 'Щойно оновлено',
    showText: 'Показати текст',
    retranscribeAccessibility: 'Повторно транскрибувати запис',
    retranscribe: '↻ Повторна транскрипція',
    quickTranslation: 'Швидкий переклад',
    ukrainian: 'Українська',
    russian: 'Російська',
    selectUkrainianTranslation: 'Вибрати переклад українською',
    selectRussianTranslation: 'Вибрати переклад російською',
    translateAgainAccessibility: 'Перекласти транскрипт ще раз',
    translateAccessibility: 'Перекласти транскрипт',
    translatingOnDevice: '… Переклад на цьому iPhone',
    translateAgainGoogle: 'Перекласти ще раз через Google',
    translateGoogle: 'Перекласти через Google',
    translationInfo: 'Працює на пристрої після завантаження мовної моделі. У перекладі зберігаються ті самі часові позиції аудіо.',
    translationAttribution: 'Автоматичний переклад на основі Google Translate',
    playTranscriptFrom: 'Відтворити транскрипт від',
    exportThisLecture: 'Експортувати цей запис',
    exportAudio: '🎧 Аудіо M4A',
    exportTranscript: '📄 Транскрипт',
    exportUkrainian: '🇺🇦 Переклад українською',
    exportTimestamps: '⏱ Текст із часовими мітками',
    exportZip: '📦 Повний ZIP',
    markedMoments: 'Позначені моменти',
    recordingInterruptedTitle: 'Запис було перервано',
    recordingInterruptedCannotTranscribe: 'iOS не завершила цей аудіофайл, тому його неможливо транскрибувати.',
    recordingInterruptedCannotPlay: 'iOS не завершила цей аудіофайл до закриття застосунку, тому його неможливо відтворити.',
    audioRecordingInvalid: 'Аудіозапис відсутній або пошкоджений.',
    whisperEmptyAfterRetry: 'WhisperKit не знайшов текст після двох спроб.',
    retranscribeTitle: 'Повторно транскрибувати запис?',
    retranscribePrompt: 'Аудіо не зміниться. Успішна нова транскрипція замінить старий транскрипт і видалить переклади, створені з нього.',
    retranscribeConfirm: 'Транскрибувати знову',
    transcriptionErrorTitle: 'Помилка транскрипції WhisperKit',
    translationErrorTitle: 'Помилка перекладу',
    transcriptEmpty: 'Транскрипт порожній.',
    noTextToTranslate: 'Немає тексту для перекладу.',
    incompleteTimestampedTranslation: 'ML Kit повернув неповний переклад із часовими мітками.',
    incompleteTranslation: 'ML Kit повернув неповний переклад.',
    emptyTranslation: 'ML Kit повернув порожній переклад.',
    exportErrorTitle: 'Помилка експорту',
    sharingUnavailable: 'На цьому пристрої недоступна функція «Поділитися».',
    sourceFileMissing: 'Вихідний файл відсутній.',
    audioFileMissing: 'Аудіофайл відсутній.',
    createTranscriptFirst: 'Спочатку створіть транскрипт.',
    createUkrainianFirst: 'Спочатку створіть переклад українською.',
    createTimestampsFirst: 'Спочатку створіть транскрипт із часовими мітками.',
    zipCreateFailed: 'Не вдалося створити ZIP-пакет.',
    timestampTextCreateFailed: 'Не вдалося створити текст із часовими мітками.',
    exportFailed: 'Не вдалося експортувати запис.',
    playbackErrorTitle: 'Помилка відтворення',
    playbackFileMissing: 'Збережений аудіофайл не існує.',
    playbackFileIncomplete: 'Збережений аудіофайл порожній або неповний',
    playbackLoadFailed: 'Не вдалося завантажити запис.',
    playbackStartFailed: 'Аудіо завантажено, але відтворення не вдалося запустити.',
    playbackDurationUnknown: 'Файл M4A існує, але iOS не вдалося визначити його тривалість.',
    seekFailed: 'Не вдалося перейти до цього моменту.',
  },
  en: {
    captureTitle: '🎙 Audio recording',
    startRecording: 'Start recording',
    idleInfo: 'Record a lecture locally as M4A or import an existing audio file. Standard recording supports iPhone lock and background recording.',
    stopRecording: 'Stop recording',
    preparingLive: 'Preparing Live…',
    live: 'Live',
    stopLive: 'Stop Live',
    liveTitle: 'Live transcription',
    livePreparing: 'Preparing the local model…',
    liveListening: 'Listening and transcribing…',
    liveFinalizing: 'Saving and finalizing…',
    liveSource: 'Original',
    liveTranslation: 'Translation',
    liveWaiting: 'Waiting for speech…',
    liveSaved: 'Live recording saved',
    liveError: 'Live error',
    close: 'Close',
    importAudio: 'Import audio file',
    supportedFormats: 'M4A, MP3, WAV, AAC, CAF or MP4',
    savedLectures: 'Saved recordings',
    savedRecording: 'Saved recording',
    emptyLibrary: 'Your saved recordings will appear here.',
    processing: 'Processing…',
    processingInProgress: 'Processing in progress',
    waitForProcessing: 'Wait until transcription or translation finishes.',
    waitForProcessingBeforeImport: 'Wait until transcription or translation finishes before importing another audio file.',
    microphonePermission: 'Microphone permission',
    microphoneRequired: 'Microphone access is required.',
    recordingError: 'Recording error',
    recordingNotSaved: 'Recording was not saved',
    activeRecordingMissing: 'The active audio recording could not be found.',
    recordingTooShort: 'The recording was too short.',
    nativeRecordingInvalid: 'The recording file is invalid or incomplete.',
    unexpectedAudioPath: 'The audio recording could not be finalized correctly.',
    audioImported: 'Audio imported',
    importFailed: 'Import failed',
    noAudioSelected: 'No audio file was selected.',
    unsupportedAudioFormat: 'Unsupported audio format. Use M4A, MP3, WAV, AAC, CAF or MP4.',
    selectedAudioInvalid: 'The selected audio file is missing or invalid.',
    selectedAudioNoDuration: 'The selected audio file has no usable duration.',
    importedAudioInvalid: 'The imported audio copy is invalid.',
    transcriptError: 'Transcript error',
    transcriptOpenFailed: 'The transcript could not be opened.',
    renameLecture: 'Rename recording',
    renamePrompt: 'Enter a name for this recording. Leave it empty to use the date again.',
    cancel: 'Cancel',
    save: 'Save',
    renameError: 'Rename error',
    renameSaveFailed: 'The recording name could not be saved.',
    deleteLecture: 'Delete recording?',
    deletePrompt: 'This permanently deletes the audio recording and transcript from this iPhone.',
    delete: 'Delete',
    deleteError: 'Delete error',
    deleteFailed: 'The recording could not be deleted.',
    useNorwegian: 'Use Norwegian for this recording',
    useEnglish: 'Use English for this recording',
    pausedForCall: '⏸ PAUSED FOR CALL',
    recording: '● RECORDING',
    callPauseInfo: '📞 Recording is safely paused for the phone call. It will resume automatically when the call ends.',
    microphoneLevel: 'Microphone level',
    microphoneNoSound: '⚠ Microphone is not receiving sound',
    microphoneQuiet: 'Signal is quiet · move the iPhone closer if possible',
    lockRecordingInfo: 'Recording continues while the iPhone is locked.',
    audioSaved: '✓ Audio saved locally as M4A',
    readyForLaterTranscription: 'Ready for later transcription.',
    markThisMoment: 'Mark this moment',
    markerImportant: '⭐ Important',
    markerUnclear: '❓ Unclear',
    markerRepeat: '🔁 Repeat',
    markerTerm: '🆕 Term',
    markMoment: '⭐ Mark moment',
    markersSaved: 'Markers saved:',
    interrupted: '⚠ Recording was interrupted',
    audioSavedShort: 'Audio saved',
    renameAccessibility: 'Rename recording',
    deleteAccessibility: 'Delete recording',
    loadingAudio: 'Loading audio…',
    back15: 'Go back 15 seconds',
    forward15: 'Go forward 15 seconds',
    back15Short: '↶ 15 sec',
    forward15Short: '15 sec ↷',
    cannotPlayInterrupted: 'Interrupted recording cannot be played',
    pauseLecture: 'Pause recording playback',
    playLecture: 'Play recording',
    noPlayback: '⚠ No playback',
    loading: '… Loading',
    pause: '⏸ Pause',
    play: '▶ Play',
    cannotTranscribeInterrupted: 'Interrupted recording cannot be transcribed',
    hideTranscript: 'Hide recording transcript',
    openTranscript: 'Open recording transcript',
    createTranscriptAccessibility: 'Create recording transcript',
    noTranscript: '⚠ No transcript',
    hideText: '📄 Hide text',
    transcript: '📄 Transcript',
    transcribing: '… Transcribing',
    createTranscript: 'Create transcript',
    closeExportMenu: 'Close export menu',
    shareOrExport: 'Share or export recording',
    exporting: '… Exporting',
    export: '✕ Export',
    shareExport: '↗ Share / Export',
    playback: 'Playback',
    interruptedDescription: 'Recording was interrupted before iOS could finalize the M4A file. Playback and transcription are disabled. You can keep/export the file for recovery or delete it.',
    preparingWhisper: 'Preparing offline Whisper model…',
    modelReady: 'Model ready',
    noTextRetrying: 'No text detected · retrying once…',
    transcribingLocally: 'Transcribing locally on this iPhone…',
    transcriptNotStarted: 'Transcript not started · WhisperKit offline',
    readyForTranscription: 'Ready for local transcription',
    transcriptionInterrupted: 'Transcription interrupted · tap Create transcript to retry',
    transcriptReady: 'Transcript ready',
    transcriptionFailedStatus: 'Transcription error · tap Create transcript to retry',
    onDevice: 'on-device',
    retranscribingPreparing: 'Re-transcribing… preparing the offline Whisper model. The existing transcript will stay visible until the new version is ready.',
    retranscribingRetrying: 'Re-transcribing… no text detected on the first pass, retrying once.',
    retranscribingLocal: 'Re-transcribing locally on this iPhone… The existing transcript will stay visible until the replacement is complete.',
    firstUseWhisper: 'First use may download the Whisper model. Keep the app open and connected to the internet.',
    processingLocally: 'Processing locally. Long recordings may take several minutes.',
    transcriptUpdated: '✓ Transcript updated',
    updatedJustNow: 'Updated just now',
    showText: 'Show text',
    retranscribeAccessibility: 'Re-transcribe recording',
    retranscribe: '↻ Re-transcribe',
    quickTranslation: 'Quick translation',
    ukrainian: 'Ukrainian',
    russian: 'Russian',
    selectUkrainianTranslation: 'Select Ukrainian translation',
    selectRussianTranslation: 'Select Russian translation',
    translateAgainAccessibility: 'Translate transcript again',
    translateAccessibility: 'Translate transcript',
    translatingOnDevice: '… Translating on this iPhone',
    translateAgainGoogle: 'Translate again with Google',
    translateGoogle: 'Translate with Google',
    translationInfo: 'On-device after the language model is downloaded. Timestamped transcripts keep the same audio positions in translation.',
    translationAttribution: 'Automatic translation powered by Google Translate',
    playTranscriptFrom: 'Play transcript from',
    exportThisLecture: 'Export this recording',
    exportAudio: '🎧 M4A audio',
    exportTranscript: '📄 Transcript',
    exportUkrainian: '🇺🇦 Ukrainian translation',
    exportTimestamps: '⏱ Text with timestamps',
    exportZip: '📦 Complete ZIP',
    markedMoments: 'Marked moments',
    recordingInterruptedTitle: 'Recording was interrupted',
    recordingInterruptedCannotTranscribe: 'This audio file was not finalized by iOS and cannot be transcribed.',
    recordingInterruptedCannotPlay: 'iOS did not finish this audio file before the app was closed, so it cannot be played.',
    audioRecordingInvalid: 'The audio recording is missing or invalid.',
    whisperEmptyAfterRetry: 'WhisperKit returned an empty transcript after two attempts.',
    retranscribeTitle: 'Re-transcribe recording?',
    retranscribePrompt: 'The audio will stay unchanged. A successful new transcript will replace the old transcript and clear translations created from it.',
    retranscribeConfirm: 'Re-transcribe',
    transcriptionErrorTitle: 'WhisperKit transcription error',
    translationErrorTitle: 'Translation error',
    transcriptEmpty: 'The transcript is empty.',
    noTextToTranslate: 'There is no text to translate.',
    incompleteTimestampedTranslation: 'ML Kit returned an incomplete timestamped translation.',
    incompleteTranslation: 'ML Kit returned an incomplete translation.',
    emptyTranslation: 'ML Kit returned an empty translation.',
    exportErrorTitle: 'Export error',
    sharingUnavailable: 'Sharing is not available on this device.',
    sourceFileMissing: 'The source file is missing.',
    audioFileMissing: 'The audio file is missing.',
    createTranscriptFirst: 'Create a transcript first.',
    createUkrainianFirst: 'Create a Ukrainian translation first.',
    createTimestampsFirst: 'Create a timestamped transcript first.',
    zipCreateFailed: 'The ZIP package could not be created.',
    timestampTextCreateFailed: 'The timestamp text could not be created.',
    exportFailed: 'The recording could not be exported.',
    playbackErrorTitle: 'Playback error',
    playbackFileMissing: 'The saved audio file does not exist.',
    playbackFileIncomplete: 'The saved audio file is empty or incomplete',
    playbackLoadFailed: 'The recording could not be loaded.',
    playbackStartFailed: 'Audio loaded, but playback could not start.',
    playbackDurationUnknown: 'The M4A exists, but iOS could not determine its duration.',
    seekFailed: 'Could not jump to this moment.',
  },
  no: {
    captureTitle: '🎙 Lydopptak',
    startRecording: 'Start opptak',
    idleInfo: 'Ta opp en forelesning lokalt som M4A, eller importer en eksisterende lydfil. Vanlig opptak støtter låst skjerm og bakgrunnsopptak.',
    stopRecording: 'Stopp opptak',
    preparingLive: 'Forbereder Live…',
    live: 'Live',
    stopLive: 'Stopp Live',
    liveTitle: 'Live-transkripsjon',
    livePreparing: 'Forbereder lokal modell…',
    liveListening: 'Lytter og transkriberer…',
    liveFinalizing: 'Lagrer og ferdigstiller…',
    liveSource: 'Original',
    liveTranslation: 'Oversettelse',
    liveWaiting: 'Venter på tale…',
    liveSaved: 'Live-opptaket er lagret',
    liveError: 'Live-feil',
    close: 'Lukk',
    importAudio: 'Importer lydfil',
    supportedFormats: 'M4A, MP3, WAV, AAC, CAF eller MP4',
    savedLectures: 'Lagrede opptak',
    savedRecording: 'Lagret opptak',
    emptyLibrary: 'Lagrede opptak vises her.',
    processing: 'Behandler…',
    processingInProgress: 'Behandling pågår',
    waitForProcessing: 'Vent til transkripsjon eller oversettelse er ferdig.',
    waitForProcessingBeforeImport: 'Vent til transkripsjon eller oversettelse er ferdig før du importerer en ny lydfil.',
    microphonePermission: 'Mikrofontilgang',
    microphoneRequired: 'Appen trenger tilgang til mikrofonen.',
    recordingError: 'Opptaksfeil',
    recordingNotSaved: 'Opptaket ble ikke lagret',
    activeRecordingMissing: 'Det aktive lydopptaket ble ikke funnet.',
    recordingTooShort: 'Opptaket var for kort.',
    nativeRecordingInvalid: 'Opptaksfilen er ugyldig eller ufullstendig.',
    unexpectedAudioPath: 'Lydopptaket kunne ikke ferdigstilles riktig.',
    audioImported: 'Lydfil importert',
    importFailed: 'Import mislyktes',
    noAudioSelected: 'Ingen lydfil ble valgt.',
    unsupportedAudioFormat: 'Lydformatet støttes ikke. Bruk M4A, MP3, WAV, AAC, CAF eller MP4.',
    selectedAudioInvalid: 'Den valgte lydfilen mangler eller er ugyldig.',
    selectedAudioNoDuration: 'Den valgte lydfilen har ingen brukbar varighet.',
    importedAudioInvalid: 'Den importerte lydkopien er ugyldig.',
    transcriptError: 'Transkripsjonsfeil',
    transcriptOpenFailed: 'Transkripsjonen kunne ikke åpnes.',
    renameLecture: 'Gi opptaket nytt navn',
    renamePrompt: 'Skriv inn et navn på opptaket. La feltet stå tomt for å bruke datoen igjen.',
    cancel: 'Avbryt',
    save: 'Lagre',
    renameError: 'Feil ved navneendring',
    renameSaveFailed: 'Navnet på opptaket kunne ikke lagres.',
    deleteLecture: 'Slette opptaket?',
    deletePrompt: 'Dette sletter lydopptaket og transkripsjonen permanent fra denne iPhonen.',
    delete: 'Slett',
    deleteError: 'Feil ved sletting',
    deleteFailed: 'Opptaket kunne ikke slettes.',
    useNorwegian: 'Bruk norsk for dette opptaket',
    useEnglish: 'Bruk engelsk for dette opptaket',
    pausedForCall: '⏸ PAUSE UNDER SAMTALE',
    recording: '● OPPTAK',
    callPauseInfo: '📞 Opptaket er trygt satt på pause under telefonsamtalen. Det fortsetter automatisk når samtalen er avsluttet.',
    microphoneLevel: 'Mikrofonnivå',
    microphoneNoSound: '⚠ Mikrofonen mottar ikke lyd',
    microphoneQuiet: 'Signalet er svakt · flytt iPhonen nærmere hvis mulig',
    lockRecordingInfo: 'Opptaket fortsetter mens iPhonen er låst.',
    audioSaved: '✓ Lyd lagret lokalt som M4A',
    readyForLaterTranscription: 'Klar for transkripsjon senere.',
    markThisMoment: 'Marker dette tidspunktet',
    markerImportant: '⭐ Viktig',
    markerUnclear: '❓ Uklart',
    markerRepeat: '🔁 Gjenta',
    markerTerm: '🆕 Begrep',
    markMoment: '⭐ Marker tidspunkt',
    markersSaved: 'Markører lagret:',
    interrupted: '⚠ Opptaket ble avbrutt',
    audioSavedShort: 'Lyd lagret',
    renameAccessibility: 'Gi opptaket nytt navn',
    deleteAccessibility: 'Slett opptaket',
    loadingAudio: 'Laster lyd…',
    back15: 'Gå 15 sekunder tilbake',
    forward15: 'Gå 15 sekunder frem',
    back15Short: '↶ 15 sek',
    forward15Short: '15 sek ↷',
    cannotPlayInterrupted: 'Et avbrutt opptak kan ikke spilles av',
    pauseLecture: 'Sett avspillingen på pause',
    playLecture: 'Spill av opptaket',
    noPlayback: '⚠ Kan ikke spilles av',
    loading: '… Laster',
    pause: '⏸ Pause',
    play: '▶ Spill av',
    cannotTranscribeInterrupted: 'Et avbrutt opptak kan ikke transkriberes',
    hideTranscript: 'Skjul transkripsjonen',
    openTranscript: 'Åpne transkripsjonen',
    createTranscriptAccessibility: 'Opprett transkripsjon',
    noTranscript: '⚠ Ingen transkripsjon',
    hideText: '📄 Skjul tekst',
    transcript: '📄 Transkripsjon',
    transcribing: '… Transkriberer',
    createTranscript: 'Opprett transkripsjon',
    closeExportMenu: 'Lukk eksportmenyen',
    shareOrExport: 'Del eller eksporter opptaket',
    exporting: '… Eksporterer',
    export: '✕ Eksport',
    shareExport: '↗ Del / Eksporter',
    playback: 'Avspilling',
    interruptedDescription: 'Opptaket ble avbrutt før iOS rakk å ferdigstille M4A-filen. Avspilling og transkripsjon er deaktivert. Du kan beholde/eksportere filen for gjenoppretting eller slette den.',
    preparingWhisper: 'Forbereder offline Whisper-modell…',
    modelReady: 'Modellen er klar',
    noTextRetrying: 'Ingen tekst oppdaget · prøver én gang til…',
    transcribingLocally: 'Transkriberer lokalt på denne iPhonen…',
    transcriptNotStarted: 'Transkripsjon ikke startet · WhisperKit offline',
    readyForTranscription: 'Klar for lokal transkripsjon',
    transcriptionInterrupted: 'Transkripsjonen ble avbrutt · trykk Opprett transkripsjon for å prøve igjen',
    transcriptReady: 'Transkripsjonen er klar',
    transcriptionFailedStatus: 'Transkripsjonsfeil · trykk Opprett transkripsjon for å prøve igjen',
    onDevice: 'på enheten',
    retranscribingPreparing: 'Transkriberer på nytt… forbereder offline Whisper-modellen. Den eksisterende transkripsjonen forblir synlig til den nye versjonen er klar.',
    retranscribingRetrying: 'Transkriberer på nytt… ingen tekst ble funnet i første forsøk, prøver én gang til.',
    retranscribingLocal: 'Transkriberer på nytt lokalt på denne iPhonen… Den eksisterende transkripsjonen forblir synlig til den nye er ferdig.',
    firstUseWhisper: 'Ved første gangs bruk kan Whisper-modellen bli lastet ned. Hold appen åpen og koblet til internett.',
    processingLocally: 'Behandles lokalt. Lange opptak kan ta flere minutter.',
    transcriptUpdated: '✓ Transkripsjonen er oppdatert',
    updatedJustNow: 'Oppdatert nå',
    showText: 'Vis tekst',
    retranscribeAccessibility: 'Transkriber opptaket på nytt',
    retranscribe: '↻ Transkriber på nytt',
    quickTranslation: 'Hurtigoversettelse',
    ukrainian: 'Ukrainsk',
    russian: 'Russisk',
    selectUkrainianTranslation: 'Velg ukrainsk oversettelse',
    selectRussianTranslation: 'Velg russisk oversettelse',
    translateAgainAccessibility: 'Oversett transkripsjonen på nytt',
    translateAccessibility: 'Oversett transkripsjonen',
    translatingOnDevice: '… Oversetter på denne iPhonen',
    translateAgainGoogle: 'Oversett på nytt med Google',
    translateGoogle: 'Oversett med Google',
    translationInfo: 'Kjører på enheten etter at språkmodellen er lastet ned. Tidskodede transkripsjoner beholder de samme lydposisjonene i oversettelsen.',
    translationAttribution: 'Automatisk oversettelse med Google Translate',
    playTranscriptFrom: 'Spill transkripsjonen fra',
    exportThisLecture: 'Eksporter dette opptaket',
    exportAudio: '🎧 M4A-lyd',
    exportTranscript: '📄 Transkripsjon',
    exportUkrainian: '🇺🇦 Ukrainsk oversettelse',
    exportTimestamps: '⏱ Tekst med tidskoder',
    exportZip: '📦 Komplett ZIP',
    markedMoments: 'Markerte tidspunkter',
    recordingInterruptedTitle: 'Opptaket ble avbrutt',
    recordingInterruptedCannotTranscribe: 'Denne lydfilen ble ikke ferdigstilt av iOS og kan derfor ikke transkriberes.',
    recordingInterruptedCannotPlay: 'iOS rakk ikke å ferdigstille denne lydfilen før appen ble lukket, så den kan ikke spilles av.',
    audioRecordingInvalid: 'Lydopptaket mangler eller er ugyldig.',
    whisperEmptyAfterRetry: 'WhisperKit fant ingen transkripsjon etter to forsøk.',
    retranscribeTitle: 'Transkribere opptaket på nytt?',
    retranscribePrompt: 'Lyden forblir uendret. En vellykket ny transkripsjon erstatter den gamle transkripsjonen og sletter oversettelser som er laget fra den.',
    retranscribeConfirm: 'Transkriber på nytt',
    transcriptionErrorTitle: 'WhisperKit-transkripsjonsfeil',
    translationErrorTitle: 'Oversettelsesfeil',
    transcriptEmpty: 'Transkripsjonen er tom.',
    noTextToTranslate: 'Det finnes ingen tekst å oversette.',
    incompleteTimestampedTranslation: 'ML Kit returnerte en ufullstendig oversettelse med tidskoder.',
    incompleteTranslation: 'ML Kit returnerte en ufullstendig oversettelse.',
    emptyTranslation: 'ML Kit returnerte en tom oversettelse.',
    exportErrorTitle: 'Eksportfeil',
    sharingUnavailable: 'Deling er ikke tilgjengelig på denne enheten.',
    sourceFileMissing: 'Kildefilen mangler.',
    audioFileMissing: 'Lydfilen mangler.',
    createTranscriptFirst: 'Opprett en transkripsjon først.',
    createUkrainianFirst: 'Opprett en ukrainsk oversettelse først.',
    createTimestampsFirst: 'Opprett en transkripsjon med tidskoder først.',
    zipCreateFailed: 'ZIP-pakken kunne ikke opprettes.',
    timestampTextCreateFailed: 'Teksten med tidskoder kunne ikke opprettes.',
    exportFailed: 'Opptaket kunne ikke eksporteres.',
    playbackErrorTitle: 'Avspillingsfeil',
    playbackFileMissing: 'Den lagrede lydfilen finnes ikke.',
    playbackFileIncomplete: 'Den lagrede lydfilen er tom eller ufullstendig',
    playbackLoadFailed: 'Opptaket kunne ikke lastes.',
    playbackStartFailed: 'Lyden ble lastet, men avspillingen kunne ikke startes.',
    playbackDurationUnknown: 'M4A-filen finnes, men iOS kunne ikke fastslå varigheten.',
    seekFailed: 'Kunne ikke hoppe til dette tidspunktet.',
  },
} as const;

export function getAudioUiText(
  value: string | null | undefined
) {
  return COPY[
    normalizeAudioUiLanguage(value)
  ];
}

export function getAudioSourceLanguageLabel(
  sourceLanguage:
    LectureSourceLanguage,
  appLanguage:
    string | null | undefined
) {
  const uiLanguage =
    normalizeAudioUiLanguage(
      appLanguage
    );

  if (
    sourceLanguage === 'en'
  ) {
    return uiLanguage === 'ua'
      ? 'Англійська'
      : uiLanguage === 'no'
        ? 'Engelsk'
        : 'English';
  }

  return uiLanguage === 'ua'
    ? 'Норвезька'
    : uiLanguage === 'no'
      ? 'Norsk'
      : 'Norwegian';
}

export function getAudioMarkerLabel(
  type:
    LectureMarkerType,
  appLanguage:
    string | null | undefined
) {
  const copy =
    getAudioUiText(
      appLanguage
    );

  switch (type) {
  case 'important':
    return copy.markerImportant;
  case 'unclear':
    return copy.markerUnclear;
  case 'repeat':
    return copy.markerRepeat;
  case 'term':
    return copy.markerTerm;
  default:
    return copy.markerImportant;
  }
}
